site_name: Vulcan Activity Tracker Docs
repo_url: https://github.com/jjdeuce06/VulcanActivityTracker
repo_name: jjdeuce06/VulcanActivityTracker

# For GitHub Pages project sites:
site_url: https://jjdeuce06.github.io/VulcanActivityTracker/

theme:
  name: material

nav:
  - Overview: index.md
  - Weekly Progress: progress/
  - Gantt Chart: progress/gantt.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom



