site_name: Vulcan Activity Tracker Docs
repo_url: https://github.com/jjdeuce06/VulcanActivityTracker
repo_name: jjdeuce06/VulcanActivityTracker

# For GitHub Pages project sites:
site_url: https://jjdeuce06.github.io/VulcanActivityTracker/

theme:
  name: material

nav:
  - Tutorial: tutorial.md
  - Overview: index.md
  # - Design: design.md
  # - Proposal: proposal.md
  # - Requirements: requirements.md
  # - Specifications: specifications.md
  - Weekly Progress: progress/index.md
  - Gantt Chart: progress/gantt.md

plugins:
  - search
  - mermaid2:
      javascript: js/mermaid.min.js
  - panzoom:
      always_show_hint: false
      hint_location: "top"
      full_screen: true
      include_selectors:
        - ".mermaid"
        - "img"

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom



