services:
  platform-dev:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vulcan_platform_dev
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_ENV: development
    volumes:
      - .:/VulcanActivityTracker
    working_dir: /VulcanActivityTracker
    ports:
      - "6455:6455"
    networks:
      - vulcan_network
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "VulcanP@ssw0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - vulcan_network

networks:
  vulcan_network:
    driver: bridge
volumes:
  mssql_data: